version: '3'
services:
  sensors-backend:
    build: ./sensors-backend
    volumes:
      - ./sensors-backend/build/libs:/app
    ports:
      - 5005:5005

  sensors-frontend:
    build: ./sensors-frontend
    volumes:
      - ./sensors-frontend:/app
    ports:
      - 3300:3000

